(()=>{
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lang=()=>document.documentElement.lang==='en'?'en':'ar';
  const t=(a,e)=>lang()==='en'?e:a;
  const text=(a,e)=>`<span data-ar="${esc(a)}" data-en="${esc(e)}">${esc(t(a,e))}</span>`;
  const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({route:'<circle cx="5" cy="6" r="2"/><circle cx="19" cy="18" r="2"/><path d="M7 6h8a4 4 0 0 1 0 8H9a4 4 0 0 0 0 8h8"/>',eye:'<path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',book:'<path d="M12 6c-3-2-7-2-10-1v15c3-1 7-1 10 1 3-2 7-2 10-1V5c-3-1-7-1-10 1Z"/><path d="M12 6v15"/>',check:'<path d="m5 12 4 4L19 6"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',chart:'<path d="M4 4v16h16M8 16v-4m5 4V8m5 8v-6"/>',layers:'<path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/>'})[name]||''}</svg>`;
  function localize(host=document){host.querySelectorAll('.pmp-entry [data-ar]').forEach(e=>e.textContent=e.dataset[lang()]);host.querySelectorAll('.pmp-entry [data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===lang())));host.querySelectorAll('.entry-path').forEach(e=>e.setAttribute('aria-label',t('مراحل المنهج','Curriculum stages')));host.querySelectorAll('.entry-steps').forEach(e=>e.setAttribute('aria-label',t('خطوات البداية','Getting started')));host.querySelectorAll('[data-password-toggle]').forEach(b=>b.setAttribute('aria-label',t(document.getElementById(b.dataset.passwordToggle).type==='password'?'إظهار كلمة المرور':'إخفاء كلمة المرور',document.getElementById(b.dataset.passwordToggle).type==='password'?'Show password':'Hide password')));}
  function frame(content,{step=1,admin=false}={}){
    const list=[['أساسيات إدارة المشاريع','Foundations','14'],['أجايل والطرق الهجينة','Agile & Hybrid','16'],['الأفراد وقيادة الفريق','People','14'],['العمليات وتسليم القيمة','Process','17'],['بيئة الأعمال','Business Environment','4']];
    return `<div class="pmp-entry notranslate" translate="no"><header class="entry-top"><a class="entry-brand" href="${admin?'../':'./'}"><span class="entry-mark">${icon('route')}</span><span>PMP<span class="entry-brand-sub">${text('مسار التعلم','Learning Journey')}</span></span></a><div class="entry-languages" aria-label="Language"><button type="button" data-language="ar" aria-pressed="${lang()==='ar'}">عربي</button><button type="button" data-language="en" aria-pressed="${lang()==='en'}">English</button></div></header><div class="entry-layout"><aside class="entry-story"><div class="entry-story-top"><span class="entry-kicker">PMP / ${text('خطوة بخطوة','STEP BY STEP')}</span><h2>${text('معرفة تتحول إلى تقدم.','Turn knowledge into progress.')}</h2><p>${text('تعلّم المفاهيم، طبّقها في التدريب، ثم اختبر جاهزيتك. رحلتك محفوظة لتكمل من حيث توقفت.','Learn the concepts, put them into practice, then test your readiness. Your journey is saved so you can pick up where you left off.')}</p></div><div class="entry-path" aria-label="${t('مراحل المنهج','Curriculum stages')}">${list.map((s,i)=>`<div class="entry-path-row"><span class="entry-path-number">0${i+1}</span><div>${text(s[0],s[1])}<small>${s[2]} ${text('درسًا','lessons')}</small></div><span class="entry-path-dot"></span></div>`).join('')}</div><div class="entry-story-foot"><div><b>65</b>${text('درسًا في مسارك','lessons in your path')}</div><div><b>3,559</b>${text('سؤالًا للتدريب','practice questions')}</div></div></aside><section class="entry-main"><ol class="entry-steps" aria-label="${t('خطوات البداية','Getting started')}">${[['دخول','Sign in'],['تأمين الحساب','Secure account'],['بداية الرحلة','Your first step']].map((s,i)=>`<li class="${i+1===step?'current':i+1<step?'done':''}" ${i+1===step?'aria-current="step"':''}><span>${i+1<step?icon('check'):i+1}</span>${text(...s)}</li>`).join('')}</ol><div class="entry-content">${content}</div><footer class="entry-footer">${icon('shield')}${text('حسابك مستقل. تقدمك يُحفظ لك وحدك.','An account of your own. Progress saved just for you.')}</footer></section></div></div>`;
  }
  function bind(host,onLanguage){host.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{const value=b.dataset.language;document.documentElement.lang=value;document.documentElement.dir=value==='ar'?'rtl':'ltr';try{localStorage.setItem('pmp-language',value);}catch{}onLanguage?.(value);localize(host);});host.querySelectorAll('[data-password-toggle]').forEach(b=>b.onclick=()=>{const field=document.getElementById(b.dataset.passwordToggle),show=field.type==='password';field.type=show?'text':'password';b.setAttribute('aria-pressed',String(show));b.setAttribute('aria-label',t(show?'إخفاء كلمة المرور':'إظهار كلمة المرور',show?'Hide password':'Show password'));});}
  function passwordField(id,labelAr,labelEn,autocomplete='current-password',minimum=''){return `<label for="${id}">${text(labelAr,labelEn)}</label><div class="entry-input"><input id="${id}" name="${id}" type="password" autocomplete="${autocomplete}" required maxlength="128" ${minimum} dir="auto"><button type="button" data-password-toggle="${id}" aria-label="${t('إظهار كلمة المرور','Show password')}" aria-pressed="false">${icon('eye')}</button></div>`;}
  function login({host,admin=false,onLanguage,message=''}){
    const u=admin?'adminUsername':'loginUser',p=admin?'adminPassword':'loginPin',form=admin?'adminLoginForm':'loginForm',button=admin?'adminLoginButton':'loginBtn',error=admin?'adminLoginError':'loginError';
    host.innerHTML=frame(`<div class="entry-eyebrow">${text(admin?'إدارة المنصة':'مرحبًا بعودتك',admin?'PLATFORM ADMINISTRATION':'WELCOME BACK')}</div><h1>${text(admin?'دخول الأدمن':'أكمل رحلتك.',admin?'Admin sign in':'Pick up your journey.')}</h1><p class="entry-description">${text(admin?'أضف المستخدمين وتابع تقدم كل رحلة من مكان واحد.':'سجّل الدخول للوصول إلى دروسك وتدريباتك ونتائجك.',admin?'Create users and follow every learning journey in one place.':'Sign in to access your lessons, practice and results.')}</p>${message?`<p class="entry-notice">${esc(message)}</p>`:''}<form id="${form}"><label for="${u}">${text('اسم المستخدم','Username')}</label><div class="entry-input"><input id="${u}" name="username" autocomplete="username" autocapitalize="none" spellcheck="false" required maxlength="32" dir="ltr" placeholder="username"></div>${passwordField(p,'كلمة المرور','Password')}<div id="${error}" class="entry-error" role="alert" aria-live="polite"></div><button id="${button}" class="entry-primary" type="submit">${text('تسجيل الدخول','Sign in')}${icon('arrow')}</button></form><div class="entry-help"><p>${text('تستخدم كلمة مرور مؤقتة؟ سيُطلب تغييرها عند أول دخول.','Using a temporary password? You will be asked to change it on your first sign-in.')}</p><details><summary>${text('ما عندك حساب؟','Need an account?')}</summary><p>${text('اطلب اسم المستخدم وكلمة المرور المؤقتة من مسؤول المنصة. بعد الدخول، تختار كلمة مرورك الخاصة.','Ask your platform administrator for a username and temporary password. You can choose your own password after signing in.')}</p></details><a href="${admin?'../':'./admin/?v=7'}">${text(admin?'العودة إلى مسار التعلم':'دخول إدارة المنصة',admin?'Back to learning':'Platform administration')}</a></div>`,{admin});bind(host,onLanguage);localize(host);
  }
  function security(host){host.innerHTML=frame(`<div class="entry-eyebrow">${text('خطوة واحدة لحساب آمن','MAKE THIS ACCOUNT YOURS')}</div><h1>${text('كلمة مرور تخصك.','A password of your own.')}</h1><p class="entry-description">${text('قبل بدء الرحلة، استبدل كلمة المرور المؤقتة بكلمة مرور خاصة بك.','Before you get started, replace your temporary password with one of your own.')}</p><form id="passwordForm">${passwordField('currentPassword','كلمة المرور الحالية','Current password')}${passwordField('newPassword','كلمة المرور الجديدة','New password','new-password','minlength="8"')}<ul class="entry-criteria" aria-live="polite"><li id="passwordLength">${icon('check')}${text('٨ أحرف على الأقل','At least 8 characters')}</li><li id="passwordDifferent">${icon('check')}${text('تختلف عن كلمة المرور الحالية','Different from your current password')}</li></ul>${passwordField('confirmPassword','تأكيد كلمة المرور','Confirm password','new-password','minlength="8"')}<div id="passwordMatch" class="entry-match" aria-live="polite"></div><div id="passwordError" class="entry-error" role="alert"></div><button id="passwordSubmit" class="entry-primary" type="submit">${text('حفظ ومتابعة','Save and continue')}${icon('arrow')}</button><button id="passwordLogout" class="entry-text-button" type="button">${text('تسجيل الخروج','Sign out')}</button></form>`,{step:2});bind(host);localize(host);
    const check=()=>{const a=host.querySelector('#currentPassword').value,b=host.querySelector('#newPassword').value,c=host.querySelector('#confirmPassword').value;host.querySelector('#passwordLength').classList.toggle('met',b.trim().length>=8);host.querySelector('#passwordDifferent').classList.toggle('met',!!b&&b!==a);const match=host.querySelector('#passwordMatch');match.textContent=c?(c===b?t('كلمتا المرور متطابقتان','Passwords match'):t('كلمتا المرور غير متطابقتين','Passwords do not match')):'';match.classList.toggle('met',!!c&&c===b);};host.querySelectorAll('input').forEach(input=>input.addEventListener('input',check));host.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',check));
  }
  function onboarding({user,preferences={},onComplete,onLanguage}){
    let host=document.getElementById('onboardingGate');if(!host){host=document.createElement('div');host.id='onboardingGate';document.body.appendChild(host);}document.body.classList.add('onboarding-locked');
    let step=1,start=preferences.start||((user.role==='admin')?'admin':'curriculum'),minutes=preferences.minutes||20;
    const choices=[...(user.role==='admin'?[['admin','إدارة المنصة','Manage the platform','أنشئ الحسابات وتابع رحلات المستخدمين.','Create accounts and follow user journeys.','chart']]:[]),['curriculum','ابدأ بالمنهج','Learn the foundations','دروس مرتبة من الأساسيات إلى بيئة الأعمال.','A structured path from foundations to business environment.','book'],['practice','تدرّب على الأسئلة','Practice questions','اختيار القسم والتدريب مع مراجعة الإجابات.','Choose a section and practise with answer reviews.','layers'],['assessment','اختبر مستواك','Check your level','اختبار يساعدك على معرفة نقطة البداية.','An assessment to help you find your starting point.','chart']];
    const draw=()=>{host.innerHTML=frame(`<div class="entry-eyebrow">${text('بداية تناسبك','A START THAT FITS YOU')} <span class="entry-substep">${step} / 2</span></div><h1>${step===1?text('كيف تحب تبدأ؟','Where would you like to start?'):text('خطوة صغيرة كل يوم.','A little progress every day.')}</h1><p class="entry-description">${step===1?text('اختر نقطة البداية. تقدر تتنقل بين جميع الميزات لاحقًا.','Choose your first step. You can explore every feature later.'):text('حدد هدفك اليومي للدراسة. يمكنك تعديله من الإعدادات.','Set a daily study target. You can update it in settings.')}</p><div class="entry-onboarding-name">${text('مرحبًا،','Welcome,')} <b>${esc(user.display_name||user.username)}</b></div>${step===1?`<div class="entry-choices">${choices.map(c=>`<button type="button" class="entry-choice ${start===c[0]?'selected':''}" data-start="${c[0]}" aria-pressed="${start===c[0]}"><span class="entry-choice-icon">${icon(c[5])}</span><span><b>${text(c[1],c[2])}</b><small>${text(c[3],c[4])}</small></span><span class="entry-choice-radio"></span></button>`).join('')}</div>`:`<div class="entry-minutes">${[10,20,30].map(m=>`<button type="button" class="entry-choice ${minutes===m?'selected':''}" data-minutes="${m}" aria-pressed="${minutes===m}">${icon('clock')}<b>${m}</b>${text('دقيقة','min')}</button>`).join('')}</div><div class="entry-summary">${icon('route')}<p>${text('رحلتك جاهزة. تقدمك ونتائجك محفوظة في حسابك، مهما كان الجهاز الذي تستخدمه.','Your journey is ready. Your progress and results stay with your account, whichever device you use.')}</p></div>`}<div class="entry-error" id="onboardingError" role="alert"></div><button id="onboardingNext" class="entry-primary">${step===1?text('متابعة','Continue'):text(start==='admin'?'فتح لوحة التحكم':'ابدأ الرحلة',start==='admin'?'Open dashboard':'Start my journey')}${icon('arrow')}</button>${step===2?`<button type="button" id="onboardingBack" class="entry-text-button">${text('رجوع','Back')}</button>`:''}`,{step:3});bind(host,value=>{onLanguage?.(value);draw();});host.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>{start=b.dataset.start;draw();});host.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{minutes=Number(b.dataset.minutes);draw();});host.querySelector('#onboardingBack')?.addEventListener('click',()=>{step=1;draw();});host.querySelector('#onboardingNext').onclick=async()=>{if(step===1){step=2;draw();return;}const button=host.querySelector('#onboardingNext');button.disabled=true;try{await onComplete({version:1,start,minutes,completedAt:new Date().toISOString()});document.body.classList.remove('onboarding-locked');host.remove();}catch{host.querySelector('#onboardingError').textContent=t('تعذر حفظ اختياراتك. تحقق من الاتصال وأعد المحاولة.','Could not save your choices. Check your connection and retry.');button.disabled=false;}};localize(host);};draw();
  }
  window.PMP_ENTRY={login,security,onboarding,localize,icon};
})();
